liquid:
  error_mode: strict
  strict_filters: true
collections:
  posts:
    permalink: episodes/:title
url: "https://thattech.show"
plugins:
  - jekyll-sitemap
collections_dir: _posts
defaults:
  -
    scope:
      path:            "confirmation.html"
    values:
      sitemap:         false
  -
    scope:
      path:            "email-change.html"
    values:
      sitemap:         false
  -
    scope:
      path:            "invitation.html"
    values:
      sitemap:         false
  -
    scope:
      path:            "recovery.html"
    values:
      sitemap:         false
  -
    scope:
      path:            "pages/episode.html"
    values:
      sitemap:         false
  -
    scope:
      path:            "_posts/*.html"
    values:
      sitemap:         true

include: ["episodes"]
