[build]
  publish = "_site"
  command = "bundle exec ruby feed.rb && jekyll build"
  
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
[[redirects]] 
  from = "/sitemap.xml"    
  to = "/sitemap.xml"
  status = 200
  
[[redirects]] 
  from = "/robots.txt"    
  to = "/robots.txt"
  status = 200

[[redirects]] 
  from = "/episode"    
  to = "/episodes.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "404.html"
  status = 404
  
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.
		cache-control = '''
		max-age=0,
		no-cache,
		no-store,
		must-revalidate'''
