backend:
  name: git-gateway
  repo: fakesamgregory/thattechshow

media_folder: "images/" # Media files will be stored in the repo under images/

collections:
  - name: "about" # Used in routes, e.g., /admin/collections/about
    label: "About" # Used in the UI
    folder: "_data/about" # The path to the folder where the documents are stored
    fields: # The fields for each document, usually in front matter
      - {label: "Content", name: "content", widget: "markdown"}
