# .github/workflows/schedule-netlify-build.yml

name: Schedule Netlify Build
on:
  schedule:
    # Customize schedule expression at crontab.guru
    # This one runs at 5:01 UTC daily
    # Discussion on when Timezone support will be added https://github.com/github/feedback/discussions/13454
    # For now we just run twice
    # - cron: "30 4 * * *"
    # - cron: "30 5 * * *"
jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/616df66f7945d53c55e1e5b2
